### ISSUE TITLE
API specification v1.0 additions

### ISSUE THREAD

**Issue by victoryprince** [ERIGrid2/JRA-3.1-api#1]
Possible additions to the API config:
- type of transport tool be used
- rate of data exchange

**Comment by stv0g** [comment]
Hi @victoryprince,

so far we havn't specified the data exchange configuration. However for the universal API:

> type of transport tool be used

The type is already provided by the `/info` API endpoint which allows the lab to query which transport is actually used.

https://github.com/ERIGrid2/JRA-3.1-api/blob/main/openapi/universal-api/components/schemas/Info.yaml#L14

I thought to use the `/config` endpoint only for user-custom settings which can be provided by the data exchange config and then queried by the lab.

> rate of data exchange

I guess this could be some meta data attribute associated with a signal?
