### ISSUE TITLE
Regex for SignalId

### ISSUE THREAD

**Issue by ewidl** [ERIGrid2/JRA-3.1-api#7]
I am not an expert for regex, but I think that there is small mistake in the regex for the ```SignalId``` (see file [SignalId.yaml](https://github.com/ERIGrid2/JRA-3.1-api/blob/6566f25c8070d09571a04e2283e599b4391aad77/openapi/universal-api/components/schemas/SignalId.yaml#L4)):

It currently says ```^[a-z0-9-_/]$```, which matches only a single character. I assume what is intended is ```^[a-z0-9-_/]+$``` (with the additional ```+```), which matches multiple characters.

**Comment by stv0g** [comment]
Hi @ewidl,

yes you are right. Thats a mistake. I fixed it in 3bd69849c128e5e11ced9fc49e2b854841fd64a4
