### ISSUE TITLE
Maximum range for complex data types

### ISSUE THREAD

**Issue by victoryprince** [ERIGrid2/JRA-3.1-api#9]
range for complex data type is undefined

**Comment by stv0g** [comment]
I agree. Gabriele and me discussed the issue also yesterday.

Is there a proper way of fixing this? Or do we consider it to be a _wont-fix_ issue?
There are also other datatypes for which no ranges are defined (e.g. boolean).

**Comment by stv0g** [comment]
@victoryprince Do you have a proposal how we can fix the issue? Otherwise I would close it as "wont-fix"

**Comment by victoryprince** [comment]
I agree. This is a known limitation, so would mark it as that.

**Comment by stv0g** [comment]
Okay, then lets close this issue. I will create a new one to document this limitation.
